---@class Keysmith.Config

---@class QuickfixEntryHelper
---Snacks
---@field buf number
---@field pos snacks.picker.Pos
---@field valid boolean
---@field text string
---
---Telescope
---@field bufnr number
---@field lnum number
---@field col number
---@field text string
---
---Fzf lua
---@field bufnr number
---@field line number
---@field col number
---@field text string

---@class Keysmith.NodeItem: QuickfixEntryHelper
---@field key string
---@field value string
---@field target_node TSNode -- To be used when jumping

---@class Keysmith.lang
---@field get_all_leaf_keysmith_nodes fun(roots: TSNode[], bufnr: number): Keysmith.NodeItem[] | nil
---@field get_all_leaf_nodes_single fun(root: TSNode, bufnr: number, prefix: string|nil): Keysmith.NodeItem[] | nil
---@field get_keysmith_node fun(opts: vim.treesitter.get_node.Opts|nil): Keysmith.NodeItem[] | nil
---@field use_lang string|nil
